---
- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    validate: /usr/sbin/visudo -cf %s
    create: yes
    mode: "0440"
- name: Ensure yay is installed
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    use: auto
    state: present

- name: Load package lists
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../vars/packages.yml"

- name: Install pacman packages
  community.general.pacman:
    name: "{{ packages }}"
    state: present

- name: Install AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    use: auto
    state: present
