---
- name: Configure Arch Linux system
  hosts: all
  connection: local

  vars_files:
    - vars/main.yml      # Shared variables
    - vars/packages.yml  # Package lists
    - vars/ssh.yml       # SSH configuration
    - vars/user.yml      # User variables
    - vars/ssh_vault.yml # SSH vault

  roles:
    - role: packages
      tags: [packages, install]

    - role: ssh
      tags: [ssh, config]
