---
- name: "Packages | Ensure base-devel and git are installed"
  become: true
  community.general.pacman:
    name:
      - base-devel
      - git
    state: present
  tags: [packages, aur, aur-helper]

- name: "Packages | Install yay AUR helper via kewlfft.aur"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  tags: [packages, aur, aur-helper]
