---
- name: "Packages | Install AUR packages"
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    use: yay
    state: present
  become_user: aur_builder
  become: true
  when: aur_packages is defined and aur_packages | length > 0
  tags: [packages, aur, aur-packages]
