---
- name: "Packages | Ensure base-devel and git are installed"
  become: true
  community.general.pacman:
    name:
      - base-devel
      - git
    state: present
  tags: [packages, aur, aur-helper]

- name: "Packages | Install pikaur AUR helper"
  kewlfft.aur.aur:
    name: pikaur
    use: makepkg
    state: present
  tags: [packages, aur, aur-helper]
