---
- name: "Packages | Create the aur_builder user"
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    comment: "AUR package builder"
    shell: /bin/bash
  tags: [packages, aur, aur-user]

- name: "Packages | Allow aur_builder to run sudo pacman without a password"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: '0644'
    validate: 'visudo -cf %s'
  tags: [packages, aur, aur-user]

- name: "Packages | Allow wheel group to become aur_builder without a password"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/12-wheel-to-aur_builder
    line: '%wheel ALL=(aur_builder) NOPASSWD: ALL'
    create: true
    mode: '0644'
    validate: 'visudo -cf %s'
  tags: [packages, aur, aur-user]

- name: "Packages | Allow wheel group to run pacman without a password"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/10-pacman-wheel
    line: '%wheel ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: '0644'
    validate: 'visudo -cf %s'
  tags: [packages, aur, aur-user]
