---
- name: "zsh | Ensure zsh is installed"
  become: true
  ansible.builtin.package:
    name: "{{ zsh_package_name }}"
    state: present
  when: zsh_install
  tags: [zsh, zsh-install]

- name: "zsh | Deploy zsh.d configuration"
  ansible.builtin.include_tasks: configure.yml
  when: zsh_deploy_config
  tags: [zsh, zsh-config]

- name: "zsh | Set as default shell"
  ansible.builtin.include_tasks: default_shell.yml
  when: zsh_set_default_shell
  tags: [zsh, zsh-default-shell]
