---
# ZSH Role - Main Tasks

- name: "zsh | Deploy zsh.d configuration"
  ansible.builtin.include_tasks: deploy_config.yml
  when: zsh_deploy_config
  tags: [zsh, zsh-config]

- name: "zsh | Deploy .zshrc file"
  ansible.builtin.include_tasks: deploy_zshrc.yml
  when: zsh_deploy_zshrc
  tags: [zsh, zsh-zshrc]
