#!/bin/zsh
export SKOGAI_CONFIG_DIR=/home/skogix/skogai/config/
# ============================================================================
# Ultra-Minimal ZSH Configuration
# All environment variables managed by: skogcli config
# ============================================================================

# ----------------------------------------------------------------------------
# Oh My Zsh Configuration
# ----------------------------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="simple"
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="false"
DISABLE_MAGIC_FUNCTIONS="true"
ENABLE_CORRECTION="false"

# Plugins
# plugins=(ssh-agent)
plugins=(
    # ssh-agent  # Disabled - using zplug version instead
    vi-mode
    direnv
    virtualenv
    themes
    pyenv
    z
    uv
    tailscale
    npm
    nvm
    zsh-navigation-tools
    ansible
)

source $ZSH/oh-my-zsh.sh



export SKOGAI="/home/skogix/skogai"
export SKOGAI_CONFIG_DIR="/home/skogix/skogai/config"

# External storage paths (matches skogcli config)
export PATH="/mnt/extra/npm/global/bin:/mnt/extra/pnpm/global/bin:$PATH"

# Go (will be set by skogcli but adding fallback)
export PATH="$PATH:$GOPATH/bin" 2>/dev/null || true



# User binaries
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/bin:$PATH"

# Development tools
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.dotnet/tools:$PATH"
export PATH="$HOME/.opencode/bin:$PATH"
export PATH="$HOME/.lmstudio/bin:$PATH"
export PATH="$HOME/.local/share/pnpm:$PATH"


# ----------------------------------------------------------------------------
# Source External Scripts
# ----------------------------------------------------------------------------
source $HOME/.local/src/aichat/scripts/shell-integration/integration.zsh
# ./$HOME/.nvm/nvm.sh
# fpath+=($HOME/.local/src/aichat/scripts/completions)
# source $HOME/.nvm/nvm-exec
source ~/.config/znt/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh


# ----------------------------------------------------------------------------
# Aliases
# ----------------------------------------------------------------------------
# Navigation & Tools
alias lg="lazygit"
alias c="clear"
alias open="xdg-open"

# Clipboard
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# Config
alias zshrc="nvim ~/.zshrc"
alias skenv="skogcli config list --env-only"
alias skadd="skogcli config add skogai.env."

# Development
alias commit='aider --commit --model openrouter/meta-llama/llama-3-8b-instruct --no-gitignore --set-env OPENROUTER_API_KEY=$OPENROUTER_API_KEY'

# System (Arch)
alias update="sudo pacman -Syu"
alias rmpkg="sudo pacman -Rsn"
alias cleanch="sudo pacman -Scc"
alias fixpacman="sudo rm /var/lib/pacman/db.lck"
alias cleanup='sudo pacman -Rsn $(pacman -Qtdq) 2>/dev/null || echo "No orphans"'
alias jctl="journalctl -p 3 -xb"
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"

# Build tools
alias make="make -j`nproc`"
alias ninja="ninja -j`nproc`"
alias n="ninja"

# ----------------------------------------------------------------------------
# Key Bindings & Options
# ----------------------------------------------------------------------------
bindkey "^P" up-line-or-search
zstyle ':completion:*' menu select

# ----------------------------------------------------------------------------
# Terminal Settings
# ----------------------------------------------------------------------------
export LESS_TERMCAP_md="$(tput bold 2> /dev/null; tput setaf 2 2> /dev/null)"
export LESS_TERMCAP_me="$(tput sgr0 2> /dev/null)"

# Custom completions
fpath+=~/.zsh-completions
fpath+=~/.zsh-completions/completions

# Initialize completions early (needed for argc-completions)
autoload -Uz compinit && compinit

# argc-completions
export ARGC_COMPLETIONS_ROOT="/home/skogix/.local/src/argc-completions"
export ARGC_COMPLETIONS_PATH="$ARGC_COMPLETIONS_ROOT/completions/linux:$ARGC_COMPLETIONS_ROOT/completions"
export PATH="$ARGC_COMPLETIONS_ROOT/bin:$PATH"
# To add completions for only the specified command, modify next line e.g. argc_scripts=( cargo git )
argc_scripts=( $(ls -p -1 "$ARGC_COMPLETIONS_ROOT/completions/linux" "$ARGC_COMPLETIONS_ROOT/completions" | sed -n 's/\.sh$//p') )

_aichat_zsh() {
    if [[ -n "$BUFFER" ]]; then
        local _old=$BUFFER
        BUFFER+="⌛"
        zle -I && zle redisplay
        BUFFER=$(aichat -e "$_old")
        zle end-of-line
    fi
}
zle -N _aichat_zsh
bindkey '\ee' _aichat_zsh

source <(argc --argc-completions zsh $argc_scripts)

source $HOME/.ssh/openrouter
export OPENROUTER_API_KEY=$OPENROUTER_API_KEY

export SKOGAI=/home/skogix/skogai
export SKOGAI_CONFIG_DIR=/home/skogix/skogai/config

# ----------------------------------------------------------------------------
# Load ALL Environment Variables from skogcli
# ----------------------------------------------------------------------------
# Everything is in the skogai namespace now
# To add/modify: skogcli config add skogai.env.VAR_NAME "value"
# To list all: skogcli config list --env-only


#
# # Check if zplug is installed
# if [[ ! -d ~/.zplug ]]; then
#     git clone https://github.com/zplug/zplug ~/.zplug
#     source ~/.zplug/init.zsh && zplug update --self
# fi
#
# # Essential
# source ~/.zplug/init.zsh
#
# # What does this do?
# # zplug "junegunn/fzf-bin", \
# #     from:gh-r, \
# #     at:0.11.0, \
# #     as:command, \
# #     use:"*darwin*amd64*", \
# #     rename-to:fzf
# # It grabs the binary of fzf-bin version 0.11.0 from GitHub Release and uses
# # the file that matches "*darwin*amd64" as a command called fzf!
#
# # plugins=( ssh-agent vi-mode direnv virtualenv themes pyenv z uv tailscale npm nvm zsh-navigation-tools ansible)
# zplug "plugins/ssh-agent",   from:oh-my-zsh
# zplug "plugins/git",   from:oh-my-zsh
# zplug "plugins/vi-mode",   from:oh-my-zsh
# zplug "plugins/direnv",   from:oh-my-zsh
# zplug "plugins/virtualenv",   from:oh-my-zsh
# zplug "plugins/themes",   from:oh-my-zsh
# zplug "plugins/pyenv",   from:oh-my-zsh
# zplug "plugins/z",   from:oh-my-zsh
# zplug "plugins/uv",   from:oh-my-zsh
# zplug "plugins/npm",   from:oh-my-zsh
# zplug "plugins/uv",   from:oh-my-zsh
# zplug "plugins/zsh-navigation-tools",   from:oh-my-zsh
# zplug "plugins/ansible",   from:oh-my-zsh
# zplug "zsh-users/zsh-history-substring-search"
# zplug "z-shell/zsh-navigation-tools",  from:github
# zplug "zsh-users/zsh-syntax-highlighting", defer:2
# zplug "zsh-users/zsh-completions"
# zplug 'zplug/zplug', hook-build:'zplug --self-manage'
# zplug "mafredri/zsh-async", from:github, defer:0
# zplug "lib/completion", from:oh-my-zsh
# zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
#
# # Install plugins if there are plugins that have not been installed
# if ! zplug check --verbose; then
#     printf "Install? [y/N]: "
#     if read -q; then
#         echo; zplug install
#     else
#         echo
#     fi
# fi
#
# # Then, source plugins and add commands to $PATH
# zplug load
#
# #####################################################################
# # completions
# #####################################################################
#
# # Enable completions
# if [ -d ~/.zsh/comp ]; then
#     fpath=(~/.zsh/comp $fpath)
#     autoload -U ~/.zsh/comp/*(:t)
# fi
#
# zstyle ':completion:*' group-name ''
# zstyle ':completion:*:messages' format '%d'
# zstyle ':completion:*:descriptions' format '%d'
# zstyle ':completion:*:options' verbose yes
# zstyle ':completion:*:values' verbose yes
# zstyle ':completion:*:options' prefix-needed yes
# zstyle ':completion:*' use-cache true
# zstyle ':completion:*:default' menu select=1
# zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'l:|=* r:|[.,_-]=* r:|=* m:{a-z}={A-Z}'
# sudo completions
# zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin
# zstyle ':completion:*' menu select
# zstyle ':completion:*' keep-prefix
# zstyle ':completion:*' completer _oldlist _complete _match _ignored _approximate _list _history
# zstyle ':completion:*:processes' command "ps -u $USER -o pid,stat,%cpu,%mem,cputime,command"
#
# # compinit already initialized earlier for argc-completions
# # autoload -U compinit; compinit -d ~/.zcompdump
#
#
# source /usr/share/nvm/init-nvm.sh
# alias gemini-cli="npx @google/gemini-cli"
#
# eval "$(skogcli config export-env --namespace skogai,uv)"
# alias fzf-pacman="pacman -Slq | fzf --preview 'pacman -Si {1}' --layout=reverse --bind 'enter:execute(sudo pacman -S {1})'"
#
# fpath+=~/.zfunc; autoload -Uz compinit; compinit
# alias qwen='node /mnt/extra/20250730-skogai-main/dev/qwen-code/scripts/start.js'
