---
# ZSH Role Handlers

- name: rebuild zsh completion cache
  ansible.builtin.shell: |
    rm -f ~/.zcompdump
    autoload -Uz compinit
    compinit
  args:
    executable: /bin/zsh
  changed_when: false

- name: source zshrc
  ansible.builtin.shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  changed_when: false
  failed_when: false
