alias ls='eza --color=always --group-directories-first'
alias ll='eza -alF --color=always --group-directories-first --icons'
alias la='eza -a --color=always --group-directories-first'
alias lsa='eza -a --color=always --group-directories-first'
alias l='eza -F --color=always --group-directories-first'
alias lt='eza -aT --color=always --group-directories-first --icons'
alias l.='eza -a | grep -E "^\."'
alias lg='lazygit'
alias c='clear'
alias open='xdg-open'
