---
- name: "zsh | Deploy zsh.d to ~/.config"
  ansible.builtin.copy:
    src: zsh.d/
    dest: "{{ ansible_user_dir }}/.config/zsh.d/"
    mode: preserve
  tags: [zsh, zsh-config]

- name: "zsh | Deploy .zshrc"
  ansible.builtin.copy:
    content: "source ~/.config/zsh.d/loader.zsh\n"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: '0644'
    backup: true
  tags: [zsh, zsh-config]
