---
galaxy_info:
  author: skogix
  description: Arch Linux package management role
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all

dependencies: []
