services:
  semaphore:
    ports:
      - 9005:3000
    image: public.ecr.aws/semaphore/pro/server:v2.16.47
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN:-skogix}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME:-skogix}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL:-emil@skogsund.se}
      SEMAPHORE_WEB_ROOT: ${SEMAPHORE_WEB_ROOT:-https://semaphore.skogai.se}
    env_file:
      - .env
    volumes:
      - ./data:/home/semaphore
      - ./config.json:/config.json
      - /tmp/semaphore:/tmp/semaphore
